# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.FileField(default='Patrick_DNA.jpeg', upload_to=posts.models.item_directory_path),
        ),
    ]
